// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("EdIlyin.FSharp.Http")>]
[<assembly: AssemblyProductAttribute("EdIlyin.FSharp.Http")>]
[<assembly: AssemblyDescriptionAttribute("HTTP decoders")>]
[<assembly: AssemblyVersionAttribute("0.0.3")>]
[<assembly: AssemblyFileVersionAttribute("0.0.3")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "EdIlyin.FSharp.Http"
    let [<Literal>] AssemblyProduct = "EdIlyin.FSharp.Http"
    let [<Literal>] AssemblyDescription = "HTTP decoders"
    let [<Literal>] AssemblyVersion = "0.0.3"
    let [<Literal>] AssemblyFileVersion = "0.0.3"
    let [<Literal>] AssemblyConfiguration = "Release"
